apiVersion: v1
kind: Service
metadata:
  name: thunder-jwks
  namespace: openchoreo-data-plane
spec:
  type: ExternalName
  externalName: thunder-service.thunder.svc.cluster.local
  ports:
    - name: http
      port: 8090
      targetPort: 8090
